refactor: rebuild project with new package name io.qzz.hightime.tool and clean structure
- Removed legacy project files and configurations
- Kept src directory intact with all existing code
- Created fresh android and ios project templates with correct package name
- Updated package.json with clean dependencies and scripts
- Added babel, metro, and TypeScript configurations
- Configured paths for '@' alias pointing to src directory

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -1,20 +1,4 @@
-#!/bin/sh
-
-#
-# Copyright 2015 the original author or authors.
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      https://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-#
+#!/usr/bin/env bash
 
 ##############################################################################
 ##
@@ -23,40 +7,41 @@
 ##############################################################################
 
 # Attempt to set APP_HOME
-# Resolve links: $0 may be a symlink
-pro_script="$0"
+# Resolve links: $0 may be a link
+PRG="$0"
 # Need this for relative symlinks.
-while [ -h "$pro_script" ] ; do
-    ls=`ls -ld "$pro_script"`
-    link=`expr "$ls" : '.*-> \(.*\)$'`
-    if expr "$link" : '/.*' > /dev/null; then
-        pro_script="$link"
-    else
-        pro_script=`dirname "$pro_script"`"/$link"
-    fi
+while [ -h "$PRG" ] ; do
+    ls -ld "$PRG"
+    link=`ls -l "$PRG" | awk '{print $NF}'`
+    case $link in
+      /*) PRG="$link" ;;
+      *) PRG=`dirname "$PRG"`"/$link" ;;
+    esac
 done
-APP_HOME=`dirname "$pro_script"`
-cd "$APP_HOME" || exit
+SAVED="`pwd`"
+cd "`dirname \"$PRG\"`/" >/dev/null
+APP_HOME="`pwd -P`"
+cd "$SAVED" >/dev/null
 
 APP_NAME="Gradle"
 APP_BASE_NAME=`basename "$0"`
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+DEFAULT_JVM_OPTS=""
 
-# Use the maximum available, or set MAX_FD != maximum possible on this system:
+# Use the maximum available, or set MAX_FD != "max"
 MAX_FD="maximum"
 
-warn () {
+warn ( ) {
     echo "$*"
-} >&2
+}
 
-die () {
+die ( ) {
     echo
     echo "$*"
     echo
     exit 1
-} >&2
+}
 
 # OS specific support (must be 'true' or 'false').
 cygwin=false
@@ -70,7 +55,7 @@ case "`uname`" in
   Darwin* )
     darwin=true
     ;;
-  MSYS* | MINGW* )
+  MINGW* )
     msys=true
     ;;
   NONSTOP* )
@@ -78,35 +63,84 @@ case "`uname`" in
     ;;
 esac
 
-CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
+# Determine the Java command to use to start the JVM.
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the java executable
+        JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+        JAVACMD="$JAVA_HOME/bin/java"
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
 
-export CLASSPATH
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+    fi
+else
+    JAVACMD="java"
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
-if [ "$darwin" = true ]; then
-    if ! command -v java &> /dev/null
-    then
-        if [[ -x "/usr/libexec/java_home" ]]; then
-            export JAVA_HOME=`/usr/libexec/java_home`
-        else
-            export JAVA_HOME="/Library/Java/Home"
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+fi
+
+# Increase the maximum file descriptors if we can.
+if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
+    MAX_FD_LIMIT=`ulimit -H -n`
+    if [ $? -eq 0 ] ; then
+        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
+            MAX_FD="$MAX_FD_LIMIT"
         fi
+        ulimit -n $MAX_FD
+        if [ $? -ne 0 ] ; then
+            warn "Could not set maximum file descriptor limit: $MAX_FD"
+        fi
+    else
+        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
     fi
 fi
 
-# For Cygwin or MSYS, switch paths to Windows format before running java
-if [ "$cygwin" = true ] || [ "$msys" = true ] ; then
-    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
-    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
-    JAVACMD=`cygpath --url "$JAVACMD"`
-
-    JAVA_HOME=`cygpath --path --mixed "$JAVA_HOME"`
-    JAVA_TOOL_OPTIONS=`cygpath --windows "$JAVA_TOOL_OPTIONS"`
+# For Darwin, add options to specify how the application appears in the dock
+if $darwin; then
+    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
 fi
 
-JAVA_TOOL_OPTIONS=" -Dfile.encoding=UTF-8" "$JAVACMD" \
-  -server \
-  -XX:+HeapDumpOnOutOfMemoryError \
-  -XX:HeapDumpPath=.  \
-  "-Xmx${GRADLE_OPTS}" \
-  -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
-  "$@"
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin ; then
+    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
+    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
+    JAVACMD=`cygpath --path --mixed "$JAVACMD"`
+
+    # We build the pattern for arguments to be converted via cygpath
+    ROOTDIRSRAW=`find -L / -maxdepth 2 -name .gradle -o -name .git 2>/dev/null`
+    SEP=""
+    for dir in $ROOTDIRSRAW ; do
+        ROOTDIRS="$ROOTDIRS$SEP$dir"
+        SEP="|"
+    done
+    OURCYGPATTERN="(^($ROOTDIRS))"
+    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
+
+    # Add a -Xmx to most Java applications
+    if [ "$?" -eq 0 ] ; then
+        GRADLE_OPTS="$GRADLE_OPTS \"-Xmx64m\" \"-Xms64m\""
+    fi
+fi
+
+# Escape application args
+save ( ) {
+    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
+    echo " "
+}
+APP_ARGS=`save "$@"`
+
+# Collect all arguments for the java command, following the shell quoting and substitution rules
+eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
+
+# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
+if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
+    cd "$(dirname "$0")"
+fi
+
+exec "$JAVACMD" "$@"
